#!/bin/bash

CLANG_FLAGS="\
-Wno-deprecated -g3"

mkdir -p generated
cd generated
bison ../cat.y -dtx --report=states,lookaheads,solved && \
flex --nounput ../cat.l && \
clang++ -I . -I .. lex.cat.c cat.tab.c ../main.cc -o ../autocatc $CLANG_FLAGS
