#!/bin/bash

# leave unmatched wildcards empty
shopt -s nullglob

mkdir -p generated
cd generated
rm -r ./*

SRC="../src"


clang -x c -E -P $SRC/cat.g4 > ./cat.g4 -Wno-invalid-pp-token
antlr4 cat.g4

cd ..

exit

CLANG_FLAGS="\
-Wno-deprecated -Wunneeded-internal-declaration \
-g3 \
-fno-caret-diagnostics -ferror-limit=999"

unbuffer \
clang++ $CLANG_FLAGS \
	-I src -I generated \
	generated/lex.cat.c \
	generated/cat.tab.c \
	src/*.cc \
	-o autocatc \
	2>&1 \
	| grep -v 'In file included'
