#!/bin/bash

CLANG_FLAGS="\
-Wno-deprecated -g3"

mkdir -p generated
cd generated
flex --nounput ../cat.l && \
bison ../cat.y -dtx --report=states,lookaheads,solved && \
clang++ -I . -I .. lex.yy.c cat.tab.c ../main.cc -o ../autocatc $CLANG_FLAGS
